"""initial tables

Revision ID: 07cfd5bac535
Revises: 
Create Date: 2026-06-27 05:30:00.809779

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07cfd5bac535'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('nit', sa.String(length=40), nullable=True),
    sa.Column('business_name', sa.String(length=180), nullable=True),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('market_location', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_full_name', 'customers', ['full_name'], unique=False)
    op.create_index('idx_customers_phone_number', 'customers', ['phone_number'], unique=False)
    op.create_table('managements',
    sa.Column('id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('customer_id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('application_code', sa.String(length=40), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('advisor_notes', sa.Text(), nullable=True),
    sa.Column('total_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('analysis_summary', sa.JSON(), nullable=True),
    sa.Column('alerts', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_managements_application_code', 'managements', ['application_code'], unique=False)
    op.create_index('idx_managements_customer_id', 'managements', ['customer_id'], unique=False)
    op.create_index('idx_managements_status', 'managements', ['status'], unique=False)
    op.create_index('idx_managements_submitted_at', 'managements', ['submitted_at'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('management_id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('customer_id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('processed_path', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('document_type_label', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_raw_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['management_id'], ['managements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_assets_customer_id', 'media_assets', ['customer_id'], unique=False)
    op.create_index('idx_media_assets_management_id', 'media_assets', ['management_id'], unique=False)
    op.create_index('idx_media_assets_status', 'media_assets', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('management_id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('customer_id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=False),
    sa.Column('media_asset_id', sa.String(length=36).with_variant(mysql.CHAR(length=36), 'mysql'), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['management_id'], ['managements.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_customer_id', 'transactions', ['customer_id'], unique=False)
    op.create_index('idx_transactions_management_id', 'transactions', ['management_id'], unique=False)
    op.create_index('idx_transactions_media_asset_id', 'transactions', ['media_asset_id'], unique=False)
    op.create_index('idx_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_transactions_type', 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_index('idx_transactions_status', table_name='transactions')
    op.drop_index('idx_transactions_media_asset_id', table_name='transactions')
    op.drop_index('idx_transactions_management_id', table_name='transactions')
    op.drop_index('idx_transactions_customer_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_media_assets_status', table_name='media_assets')
    op.drop_index('idx_media_assets_management_id', table_name='media_assets')
    op.drop_index('idx_media_assets_customer_id', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('idx_managements_submitted_at', table_name='managements')
    op.drop_index('idx_managements_status', table_name='managements')
    op.drop_index('idx_managements_customer_id', table_name='managements')
    op.drop_index('idx_managements_application_code', table_name='managements')
    op.drop_table('managements')
    op.drop_index('idx_customers_phone_number', table_name='customers')
    op.drop_index('idx_customers_full_name', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
